import {
  Versions,
  Groupings,
  Locations,
  Departments,
  Institutions,
  Roles,
  FirstNames,
  LastNames,
  Positions,
} from "./data/types";
import {
  versionY,
  versionX,
  versionMidX,
  versionBottomY,
  nodeX,
  nodeY,
} from "./data/functions";
import type { TVersionData, TGroupingData, TPerson } from "./data/types";

export const versionData: TVersionData = {
  [Versions.ONE]: {
    id: Versions.ONE,
    label: Versions.ONE,
    getX: versionX,
    getY: (windowHeight: number) => {
      return versionY(windowHeight);
    },
    getMidX: versionMidX,
    getBottomY: versionBottomY,
  },
  [Versions.TWO]: {
    id: Versions.TWO,
    label: Versions.TWO,
    getX: versionX,
    getY: versionY,
    getMidX: versionMidX,
    getBottomY: versionBottomY,
  },
  [Versions.THREE]: {
    id: Versions.THREE,
    label: Versions.THREE,
    getX: versionX,
    getY: (windowHeight: number) => {
      return versionY(windowHeight);
    },
    getMidX: versionMidX,
    getBottomY: versionBottomY,
  },
};

export const groupingData: TGroupingData = {
  [Groupings.L]: {
    [Locations.ATL]: {
      id: 0,
      label: Locations.ATL,
      x: 0.32,
      y: 0.36,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Locations.NY]: {
      id: 1,
      label: Locations.NY,
      x: 0.35,
      y: 0.7,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Locations.BK]: {
      id: 2,
      label: Locations.BK,
      x: 0.71,
      y: 0.43,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Locations.LA]: {
      id: 3,
      label: Locations.LA,
      x: 0.67,
      y: 0.67,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Locations.SHI]: {
      id: 4,
      label: Locations.SHI,
      x: 0.78,
      y: 0.22,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Locations.BJ]: {
      id: 5,
      label: Locations.BJ,
      x: 0.9,
      y: 0.3,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
  },
  [Groupings.D]: {
    [Departments.E]: {
      id: 0,
      label: Departments.E,
      x: 0.28,
      y: 0.39,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.L]: {
      id: 1,
      label: Departments.L,
      x: 0.49,
      y: 0.36,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.MC]: {
      id: 2,
      label: Departments.MC,
      x: 0.81,
      y: 0.34,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.Q]: {
      id: 3,
      label: Departments.Q,
      x: 0.67,
      y: 0.87,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.G]: {
      id: 4,
      label: Departments.G,
      x: 0.9,
      y: 0.58,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.I]: {
      id: 5,
      label: Departments.I,
      x: 0.79,
      y: 0.49,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.ECDS]: {
      id: 6,
      label: Departments.ECDS,
      x: 0.5,
      y: 0.22,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.CS]: {
      id: 7,
      label: Departments.CS,
      x: 0.38,
      y: 0.56,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.D]: {
      id: 8,
      label: Departments.D,
      x: 0.18,
      y: 0.6,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Departments.V]: {
      id: 9,
      label: Departments.V,
      x: 0.53,
      y: 0.72,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
  },
  [Groupings.I]: {
    [Institutions.E]: {
      id: 0,
      label: Institutions.E,
      x: 0.15,
      y: 0.32,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Institutions.T]: {
      id: 1,
      label: Institutions.T,
      x: 0.88,
      y: 0.38,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Institutions.N]: {
      id: 2,
      label: Institutions.N,
      x: 0.32,
      y: 0.82,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Institutions.B]: {
      id: 3,
      label: Institutions.B,
      x: 0.65,
      y: 0.65,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Institutions.P]: {
      id: 4,
      label: Institutions.P,
      x: 0.6,
      y: 0.77,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
  },
  [Groupings.R]: {
    [Roles.DE]: {
      id: 0,
      label: Roles.DE,
      x: 0.25,
      y: 0.3,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Roles.R]: {
      id: 1,
      label: Roles.R,
      x: 0.24,
      y: 0.58,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Roles.DV]: {
      id: 2,
      label: Roles.DV,
      x: 0.68,
      y: 0.39,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Roles.W]: {
      id: 3,
      label: Roles.W,
      x: 0.09,
      y: 0.56,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
  },
  [Groupings.P]: {
    [Positions.F]: {
      id: 0,
      label: Positions.F,
      x: 0.1,
      y: 0.35,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Positions.U]: {
      id: 1,
      label: Positions.U,
      x: 0.86,
      y: 0.46,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Positions.G]: {
      id: 2,
      label: Positions.G,
      x: 0.56,
      y: 0.36,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Positions.R]: {
      id: 3,
      label: Positions.R,
      x: 0.3,
      y: 0.29,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Positions.D]: {
      id: 4,
      label: Positions.D,
      x: 0.24,
      y: 0.5,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
    [Positions.EX]: {
      id: 5,
      label: Positions.EX,
      x: 0.1,
      y: 0.69,
      getX: nodeX,
      getY: nodeY,
      opacity: 0,
    },
  },
};

export const peopleData: TPerson[] = [
  {
    id: FirstNames.LK,
    firstName: FirstNames.LK,
    lastName: LastNames.LK,
    label: `${FirstNames.LK} ${LastNames.LK}`,
    versions: [
      versionData[Versions.ONE],
      versionData[Versions.TWO],
      versionData[Versions.THREE],
    ],
    institutions: [
      groupingData[Groupings.I][Institutions.T],
      groupingData[Groupings.I][Institutions.E],
    ],
    roles: [
      groupingData[Groupings.R][Roles.R],
      groupingData[Groupings.R][Roles.W],
    ],
    departments: [
      groupingData[Groupings.D][Departments.E],
      groupingData[Groupings.D][Departments.L],
      groupingData[Groupings.D][Departments.MC],
      groupingData[Groupings.D][Departments.Q],
    ],
    positions: [groupingData[Groupings.P][Positions.F]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.17,
    x: 0.17,
    getX: nodeX,
    defaultY: 0.75,
    y: 0.75,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.19, y: 0.25 },
      [Groupings.D]: { x: 0.56, y: 0.44 },
      [Groupings.R]: { x: 0.12, y: 0.46 },
      [Groupings.I]: { x: 0.5, y: 0.22 },
      [Groupings.P]: { x: 0.15, y: 0.24 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.TS,
    firstName: FirstNames.TS,
    lastName: LastNames.TS,
    label: `${FirstNames.TS} ${LastNames.TS}`,
    versions: [versionData[Versions.TWO], versionData[Versions.THREE]],
    institutions: [
      groupingData[Groupings.I][Institutions.N],
      groupingData[Groupings.I][Institutions.E],
    ],
    roles: [
      groupingData[Groupings.R][Roles.DE],
      groupingData[Groupings.R][Roles.DV],
    ],
    departments: [
      groupingData[Groupings.D][Departments.G],
      groupingData[Groupings.D][Departments.I],
      groupingData[Groupings.D][Departments.Q],
    ],
    positions: [
      groupingData[Groupings.P][Positions.U],
      groupingData[Groupings.P][Positions.G],
      groupingData[Groupings.P][Positions.R],
    ],
    locations: [groupingData[Groupings.L][Locations.NY]],
    defaultX: 0.35,
    x: 0.35,
    getX: nodeX,
    defaultY: 0.65,
    y: 0.65,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.2, y: 0.65 },
      [Groupings.D]: { x: 0.8, y: 0.74 },
      [Groupings.R]: { x: 0.48, y: 0.36 },
      [Groupings.I]: { x: 0.45, y: 0.45 },
      [Groupings.P]: { x: 0.54, y: 0.22 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.JV,
    firstName: FirstNames.JV,
    lastName: LastNames.JV,
    label: `${FirstNames.JV} ${LastNames.JV}`,
    versions: [versionData[Versions.THREE]],
    institutions: [groupingData[Groupings.I][Institutions.E]],
    roles: [groupingData[Groupings.R][Roles.DV]],
    departments: [groupingData[Groupings.D][Departments.ECDS]],
    positions: [groupingData[Groupings.P][Positions.R]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.85,
    x: 0.85,
    getX: nodeX,
    defaultY: 0.8,
    y: 0.8,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.34, y: 0.23 },
      [Groupings.D]: { x: 0.35, y: 0.3 },
      [Groupings.R]: { x: 0.84, y: 0.36 },
      [Groupings.I]: { x: 0.1, y: 0.45 },
      [Groupings.P]: { x: 0.31, y: 0.42 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.NY,
    firstName: FirstNames.NY,
    lastName: LastNames.NY,
    label: `${FirstNames.NY} ${LastNames.NY}`,
    versions: [versionData[Versions.TWO], versionData[Versions.THREE]],
    institutions: [groupingData[Groupings.I][Institutions.N]],
    roles: [groupingData[Groupings.R][Roles.DV]],
    departments: [groupingData[Groupings.D][Departments.CS]],
    positions: [groupingData[Groupings.P][Positions.U]],
    locations: [groupingData[Groupings.L][Locations.NY]],
    defaultX: 0.65,
    x: 0.65,
    getX: nodeX,
    defaultY: 0.55,
    y: 0.55,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.43, y: 0.61 },
      [Groupings.D]: { x: 0.1, y: 0.45 },
      [Groupings.R]: { x: 0.88, y: 0.48 },
      [Groupings.I]: { x: 0.12, y: 0.62 },
      [Groupings.P]: { x: 0.72, y: 0.24 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.DJ,
    firstName: FirstNames.DJ,
    lastName: LastNames.DJ,
    label: `${FirstNames.DJ} ${LastNames.DJ}`,
    versions: [
      versionData[Versions.ONE],
      versionData[Versions.TWO],
      versionData[Versions.THREE],
    ],
    institutions: [groupingData[Groupings.I][Institutions.T]],
    roles: [
      groupingData[Groupings.R][Roles.DE],
      groupingData[Groupings.R][Roles.DV],
    ],
    departments: [groupingData[Groupings.D][Departments.CS]],
    positions: [groupingData[Groupings.P][Positions.U]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.35,
    x: 0.35,
    getX: nodeX,
    defaultY: 0.3,
    y: 0.3,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.11, y: 0.33 },
      [Groupings.D]: { x: 0.1, y: 0.36 },
      [Groupings.R]: { x: 0.82, y: 0.22 },
      [Groupings.I]: { x: 0.91, y: 0.22 },
      [Groupings.P]: { x: 0.91, y: 0.72 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.JF,
    firstName: FirstNames.JF,
    lastName: LastNames.JF,
    label: `${FirstNames.JF} ${LastNames.JF}`,
    versions: [
      versionData[Versions.ONE],
      versionData[Versions.TWO],
      versionData[Versions.THREE],
    ],
    institutions: [
      groupingData[Groupings.I][Institutions.T],
      groupingData[Groupings.I][Institutions.B],
    ],
    roles: [groupingData[Groupings.R][Roles.DV]],
    departments: [groupingData[Groupings.D][Departments.CS]],
    positions: [
      groupingData[Groupings.P][Positions.U],
      groupingData[Groupings.P][Positions.G],
    ],
    locations: [
      groupingData[Groupings.L][Locations.ATL],
      groupingData[Groupings.L][Locations.BK],
    ],
    defaultX: 0.48,
    x: 0.48,
    getX: nodeX,
    defaultY: 0.48,
    y: 0.48,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.52, y: 0.42 },
      [Groupings.D]: { x: 0.1, y: 0.52 },
      [Groupings.R]: { x: 0.74, y: 0.54 },
      [Groupings.I]: { x: 0.66, y: 0.52 },
      [Groupings.P]: { x: 0.64, y: 0.54 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.AM,
    firstName: FirstNames.AM,
    lastName: LastNames.AM,
    label: `${FirstNames.AM} ${LastNames.AM}`,
    versions: [versionData[Versions.TWO], versionData[Versions.THREE]],
    institutions: [groupingData[Groupings.I][Institutions.E]],
    roles: [
      groupingData[Groupings.R][Roles.DE],
      groupingData[Groupings.R][Roles.DV],
    ],
    departments: [
      groupingData[Groupings.D][Departments.CS],
      groupingData[Groupings.D][Departments.V],
    ],
    positions: [groupingData[Groupings.P][Positions.U]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.61,
    x: 0.61,
    getX: nodeX,
    defaultY: 0.33,
    y: 0.33,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.68, y: 0.34 },
      [Groupings.D]: { x: 0.51, y: 0.63 },
      [Groupings.R]: { x: 0.5, y: 0.55 },
      [Groupings.I]: { x: 0.1, y: 0.22 },
      [Groupings.P]: { x: 0.89, y: 0.28 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.SL,
    firstName: FirstNames.SL,
    lastName: LastNames.SL,
    label: `${FirstNames.SL} ${LastNames.SL}`,
    versions: [versionData[Versions.THREE]],
    institutions: [groupingData[Groupings.I][Institutions.E]],
    roles: [
      groupingData[Groupings.R][Roles.DE],
      groupingData[Groupings.R][Roles.DV],
    ],
    departments: [groupingData[Groupings.D][Departments.CS]],
    positions: [groupingData[Groupings.P][Positions.D]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.92,
    x: 0.92,
    getX: nodeX,
    defaultY: 0.46,
    y: 0.46,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.56, y: 0.3 },
      [Groupings.D]: { x: 0.38, y: 0.48 },
      [Groupings.R]: { x: 0.5, y: 0.66 },
      [Groupings.I]: { x: 0.21, y: 0.24 },
      [Groupings.P]: { x: 0.15, y: 0.58 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.MA,
    firstName: FirstNames.MA,
    lastName: LastNames.MA,
    label: `${FirstNames.MA} ${LastNames.MA}`,
    versions: [versionData[Versions.THREE]],
    institutions: [groupingData[Groupings.I][Institutions.E]],
    roles: [
      groupingData[Groupings.R][Roles.R],
      groupingData[Groupings.R][Roles.W],
    ],
    departments: [groupingData[Groupings.D][Departments.E]],
    positions: [groupingData[Groupings.P][Positions.D]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.88,
    x: 0.88,
    getX: nodeX,
    defaultY: 0.25,
    y: 0.25,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.35, y: 0.47 },
      [Groupings.D]: { x: 0.18, y: 0.28 },
      [Groupings.R]: { x: 0.19, y: 0.72 },
      [Groupings.I]: { x: 0.38, y: 0.31 },
      [Groupings.P]: { x: 0.1, y: 0.5 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.ZF,
    firstName: FirstNames.ZF,
    lastName: LastNames.ZF,
    label: `${FirstNames.ZF} ${LastNames.ZF}`,
    versions: [versionData[Versions.TWO], versionData[Versions.THREE]],
    institutions: [groupingData[Groupings.I][Institutions.E]],
    roles: [
      groupingData[Groupings.R][Roles.DE],
      groupingData[Groupings.R][Roles.DV],
    ],
    departments: [groupingData[Groupings.D][Departments.Q]],
    positions: [groupingData[Groupings.P][Positions.U]],
    locations: [
      groupingData[Groupings.L][Locations.SHI],
      groupingData[Groupings.L][Locations.ATL],
    ],
    defaultX: 0.51,
    x: 0.51,
    getX: nodeX,
    defaultY: 0.72,
    y: 0.72,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.52, y: 0.22 },
      [Groupings.D]: { x: 0.26, y: 0.86 },
      [Groupings.R]: { x: 0.52, y: 0.46 },
      [Groupings.I]: { x: 0.3, y: 0.52 },
      [Groupings.P]: { x: 0.81, y: 0.82 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.YL,
    firstName: FirstNames.YL,
    lastName: LastNames.YL,
    label: `${FirstNames.YL} ${LastNames.YL}`,
    versions: [versionData[Versions.THREE]],
    institutions: [groupingData[Groupings.I][Institutions.E]],
    roles: [
      groupingData[Groupings.R][Roles.DE],
      groupingData[Groupings.R][Roles.DV],
    ],
    departments: [groupingData[Groupings.D][Departments.ECDS]],
    positions: [groupingData[Groupings.P][Positions.R]],
    locations: [
      groupingData[Groupings.L][Locations.SHI],
      groupingData[Groupings.L][Locations.BJ],
      groupingData[Groupings.L][Locations.ATL],
    ],
    defaultX: 0.76,
    x: 0.76,
    getX: nodeX,
    defaultY: 0.67,
    y: 0.67,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.88, y: 0.4 },
      [Groupings.D]: { x: 0.61, y: 0.3 },
      [Groupings.R]: { x: 0.64, y: 0.3 },
      [Groupings.I]: { x: 0.52, y: 0.37 },
      [Groupings.P]: { x: 0.2, y: 0.4 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.SM,
    firstName: FirstNames.SM,
    lastName: LastNames.SM,
    label: `${FirstNames.SM} ${LastNames.SM}`,
    versions: [versionData[Versions.TWO], versionData[Versions.THREE]],
    institutions: [groupingData[Groupings.I][Institutions.P]],
    roles: [groupingData[Groupings.R][Roles.DE]],
    departments: [],
    positions: [groupingData[Groupings.P][Positions.EX]],
    locations: [groupingData[Groupings.L][Locations.LA]],
    defaultX: 0.69,
    x: 0.69,
    getX: nodeX,
    defaultY: 0.82,
    y: 0.82,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.77, y: 0.56 },
      [Groupings.D]: { x: 0.85, y: 0.21 },
      [Groupings.R]: { x: 0.12, y: 0.24 },
      [Groupings.I]: { x: 0.51, y: 0.62 },
      [Groupings.P]: { x: 0.28, y: 0.69 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.QT,
    firstName: FirstNames.QT,
    lastName: LastNames.QT,
    label: `${FirstNames.QT} ${LastNames.QT}`,
    versions: [versionData[Versions.ONE]],
    institutions: [groupingData[Groupings.I][Institutions.T]],
    roles: [groupingData[Groupings.R][Roles.DE]],
    departments: [groupingData[Groupings.D][Departments.D]],
    positions: [groupingData[Groupings.P][Positions.G]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.17,
    x: 0.17,
    getX: nodeX,
    defaultY: 0.27,
    y: 0.27,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.56, y: 0.53 },
      [Groupings.D]: { x: 0.08, y: 0.72 },
      [Groupings.R]: { x: 0.31, y: 0.22 },
      [Groupings.I]: { x: 0.68, y: 0.38 },
      [Groupings.P]: { x: 0.5, y: 0.62 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.AH,
    firstName: FirstNames.AH,
    lastName: LastNames.AH,
    label: `${FirstNames.AH} ${LastNames.AH}`,
    versions: [versionData[Versions.ONE]],
    institutions: [groupingData[Groupings.I][Institutions.T]],
    roles: [
      groupingData[Groupings.R][Roles.DE],
      groupingData[Groupings.R][Roles.DV],
    ],
    departments: [groupingData[Groupings.D][Departments.CS]],
    positions: [groupingData[Groupings.P][Positions.U]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.25,
    x: 0.25,
    getX: nodeX,
    defaultY: 0.45,
    y: 0.45,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.16, y: 0.42 },
      [Groupings.D]: { x: 0.36, y: 0.66 },
      [Groupings.R]: { x: 0.5, y: 0.8 },
      [Groupings.I]: { x: 0.8, y: 0.58 },
      [Groupings.P]: { x: 0.74, y: 0.72 },
    },
    opacity: 1,
  },
  {
    id: FirstNames.MO,
    firstName: FirstNames.MO,
    lastName: LastNames.MO,
    label: `${FirstNames.MO} ${LastNames.MO}`,
    versions: [versionData[Versions.ONE]],
    institutions: [groupingData[Groupings.I][Institutions.T]],
    roles: [groupingData[Groupings.R][Roles.DE]],
    departments: [groupingData[Groupings.D][Departments.D]],
    positions: [groupingData[Groupings.P][Positions.G]],
    locations: [groupingData[Groupings.L][Locations.ATL]],
    defaultX: 0.2,
    x: 0.2,
    getX: nodeX,
    defaultY: 0.55,
    y: 0.55,
    getY: nodeY,
    groupingsXY: {
      [Groupings.L]: { x: 0.2, y: 0.55 },
      [Groupings.D]: { x: 0.26, y: 0.72 },
      [Groupings.R]: { x: 0.1, y: 0.36 },
      [Groupings.I]: { x: 0.89, y: 0.82 },
      [Groupings.P]: { x: 0.41, y: 0.52 },
    },
    opacity: 1,
  },
];
