import {chapterMeta} from "./app/data/chapterMeta";
import type { Config } from 'tailwindcss'

export default {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  important: true,
  media: false, // or 'media' or 'class'
  theme: {
    screens: {
      sm: "640px",
      // => @media (min-width: 640px) { ... }

      md: "768px",
      // => @media (min-width: 768px) { ... }

      lg: "1024px",
      // => @media (min-width: 1024px) { ... }

      xl: "1280px",
      // => @media (min-width: 1280px) { ... }

      "2xl": "1536px",
      // => @media (min-width: 1536px) { ... }
      "3xl": "1896px",
      // => @media (min-width: 1536px) { ... }
    },
    extend: {
      fontFamily: {
        power: ["VTC Du Bois, serif", { fontFeatureSettings: ' "ss06"' }],
        powerWide: ["VTC Du Bois Wide", "serif"],
        powerLightWide: ["VTC Du Bois Light Wide", "serif"],
        powerNarrow: ["VTC Du Bois Narrow", "serif"],
        powerLightNarrow: ["VTC Du Bois Light Narrow", "serif"],
        neueMontreal: ["PPNeueMontreal"],
        neueMontrealBold: ["PPNeueMontreal Bold"],
        neueMontrealLight: ["PPNeueMontreal Light"],
        sans: ["PPNeueMontreal", "sans-serif"],
        icons: ["DxD Icons"],
      },
      spacing: {
        18: "4.5rem",
      },
      gridTemplateColumns: {
        14: "repeat(14, minmax(0, 1fr))",
      },
      backgroundImage: {
        data: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('${chapterMeta.data.bgImage}')`,
        power: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('${chapterMeta.power.bgImage}')`,
        intro: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('${chapterMeta.intro.bgImage}')`,
        work: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('${chapterMeta.work.bgImage}')`,
        process: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('${chapterMeta.process.bgImage}')`,
        image: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('${chapterMeta.image.bgImage}')`,
        people: `linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url('${chapterMeta.people.bgImage}')`,
      },
      colors: {
        black: "#1C1817",
        offblack: "#1C1817",
        offwhite: "#FDF9F6",
        nightingale_blue: "#3B6FE0",
        processOrange: "rgb(219, 136, 42)",
        dataSecondary: {
          DEFAULT: "#E0DCF2",
          translucent: "#E0DCF2CC",
        },
        dataPrimary: {
          DEFAULT: "#8C20E1",
          translucent: "#8c20e1cc",
        },
        powerTextColor: "white",
        powerSecondary: {
          DEFAULT: "#FFD3D3",
          translucent: "#FFD3D3CC",
        },
        powerPrimary: {
          DEFAULT: "#D92944",
          translucent: "#D92944CC",
        },
        imageSecondary: {
          DEFAULT: "#D1E4FF",
          translucent: "#D1E4FFCC",
        },
        imagePrimary: {
          DEFAULT: "#3B4BE0",
          translucent: "#3B4BE0CC",
        },
        processSecondary: {
          DEFAULT: "#DBF5E9",
          translucent: "#DBF5E9CC",
        },
        processPrimary: {
          DEFAULT: "#9AE4C1",
          translucent: "#9AE4C1CC",
        },
        workPrimary: {
          DEFAULT: "#BB9AEC",
        },
        workSecondary: {
          DEFAULT: "#DFD2DE",
        },
        processPrimaryHalfOpacity: "#9ae4c180",
        peoplePrimary: "#FFE4D0",
        peopleSecondary: "#fac88d",
        peopleAccent:"#FEFFC9",
        processChartBackground: "#d9bb9f",
        willardSecondary: "#FEFFC9",
        willardPrimary: "#FEC313",
        England: "rgb(119,43,21)",
        France: "rgb(60,100,100)",
        Americas: "rgb(222,145,49)",
        Holland: "rgb(68,108,73)",
        Sweden: "rgb(217,182,17)",
        Spain: "rgb(209, 42, 5)",
        Native: "url(#diagonalHatch)",
        Mexico: "rgb(209, 42, 5)",
        playfairChart: "#F3ECCB",
      },
      inset: {
        screen: "100vh",
        "-screen": "-100vh",
      },
      fontSize: {
        frontTitle: "8rem",
      },
      lineHeight: {
        veryTight: "0.8",
      },
    },
  },
  variants: {
    extend: {},
  },
  safelist: [
    "bg-peopleAccent",
    "peopleAccent",
    "bg-dataPrimary",
    "bg-workPrimary",
    "border-dataPrimary",
    "border-l-dataPrimary",
    "border-l-peoplePrimary",
    "border-l-processPrimary",
    "border-l-imagePrimary",
    "border-l-powerPrimary",
    "stroke-dataPrimary",
    "stroke-peoplePrimary",
    "stroke-processPrimary",
    "stroke-imagePrimary",
    "stroke-powerPrimary",
    "stroke-workPrimary",
    "fill-dataPrimary",
    "fill-peoplePrimary",
    "fill-processPrimary",
    "fill-processOrange",
    "fill-imagePrimary",
    "fill-powerPrimary",
    "fill-dataSecondary",
    "fill-dataPrimary/50",
    "fill-peoplePrimary/50",
    "fill-processPrimary/50",
    "fill-imagePrimary/50",
    "fill-powerPrimary/50",
    "fill-dataSecondary/50",
    "fill-offwhite",
    "fill-offblack",
    "hover:bg-dataSecondary",
    "hover:bg-peopleSecondary",
    "hover:bg-processSecondary",
    "hover:bg-imageSecondary",
    "hover:bg-powerSecondary",
    "hover:bg-dataPrimary",
    "hover:bg-peoplePrimary",
    "hover:bg-processPrimary",
    "hover:bg-imagePrimary",
    "hover:bg-powerPrimary",
    "hover:fill-dataPrimary",
    "hover:fill-peoplePrimary",
    "hover:fill-processPrimary",
    "hover:fill-imagePrimary",
    "hover:fill-powerPrimary",
    "hover:stroke-dataPrimary",
    "hover:stroke-peoplePrimary",
    "hover:stroke-processPrimary",
    "hover:stroke-imagePrimary",
    "hover:stroke-powerPrimary",
    "text-dataPrimary",
    "bg-dataSecondary",
    "bg-dataPrimary-translucent",
    "bg-dataSecondary-translucent",
    "bg-powerPrimary",
    "bg-powerSecondary",
    "text-powerPrimary",
    "text-imagePrimary",
    "hover:text-powerPrimary",
    "hover:text-imagePrimary",
    "focus:text-powerPrimary",
    "focus:text-imagePrimary",
    "hover:text-processPrimary",
    "focus:text-processPrimary",
    "hover:text-workPrimary",
    "focus:text-workPrimary",
    "hover:text-peoplePrimary",
    "focus:text-peoplePrimary",
    "hover:text-dataPrimary",
    "focus:text-dataPrimary",
    "bg-imagePrimary",
    "bg-imagePrimary-translucent",
    "bg-imageSecondary",
    "bg-imageSecondary-translucent",
    "bg-powerPrimary-translucent",
    "bg-playfairChart",
    "bg-peoplePrimary",
    "bg-peopleSecondary",
    "text-processPrimary",
    "text-processOrange",
    "bg-processPrimary",
    "bg-processSecondary",
    "bg-processPrimary-translucent",
    "transition-opacity",
    "opacity-0",
    "opacity-10",
    "opacity-25",
    "opacity-100",
    "duration-700",
    "text-offblack",
    "font-extrabold",
    "bg-England",
    "bg-France",
    "bg-Americas",
    "bg-Holland",
    "bg-Sweden",
    "bg-Spain",
    "bg-Native",
    "bg-Mexico",
    "font-icons",
    "outline-4",
    "outline-red-500",
    "outline-solid",
    "scale-0",
    "scale-100",
    "stroke-white",
    "fill-white",
    "fill-black",
    "fill-yellow-500",
    "stroke-yellow-500",
    "fill-gray-300",
    "fill-gray-50",
    "text-green-400",
    "text-red-600",
    "text-red-800",
    "text-lime-500",
    "top-12",
    "top-24",
    "top-32",
    "md:scale-0",
    "h-0",
    "h-24",
    "h-48",
    "h-2/5",
    "h-20",
    "h-[80vh]",
    "h-[125vh]",
    "grid-rows-1",
    "drop-shadow-2xl",
    "underline-offset-8",
    "translate-x-[2px]",
    "md:-mx-64",
    "border-opacity-0",
    "border-opacity-70",
    "opacity-20",
    "md:mt-28",
    ...Object.keys(chapterMeta).map((chapter) => `bg-${chapter}`),
    ...Object.keys(chapterMeta).map((chapter) => `hover:bg-${chapter}`),
    ...Object.keys(chapterMeta).map((chapter) => `selection:bg-${chapter}Primary`),
    ...Object.keys(chapterMeta).map((chapter) => `selection:bg-${chapter}Secondary`),
    ...Object.keys(chapterMeta).map((chapter) => `outline-${chapter}Primary`),
    ...Object.keys(chapterMeta).map((chapter) => `outline-${chapter}Secondary`),
  ],
} satisfies Config;
