// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/chapters": {
    params: {};
  };
  "/chapters/shanawdithit": {
    params: {};
  };
  "/chapters/description": {
    params: {};
  };
  "/chapters/playfair": {
    params: {};
  };
  "/chapters/peabody": {
    params: {};
  };
  "/chapters/preface": {
    params: {};
  };
  "/chapters/process": {
    params: {};
  };
  "/chapters/dubois": {
    params: {};
  };
  "/chapters/people": {
    params: {};
  };
  "/chapters/image": {
    params: {};
  };
  "/chapters/intro": {
    params: {};
  };
  "/chapters/labor": {
    params: {};
  };
  "/chapters/power": {
    params: {};
  };
  "/chapters/data": {
    params: {};
  };
  "/chapters/work": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/chapters" | "/chapters/shanawdithit" | "/chapters/description" | "/chapters/playfair" | "/chapters/peabody" | "/chapters/preface" | "/chapters/process" | "/chapters/dubois" | "/chapters/people" | "/chapters/image" | "/chapters/intro" | "/chapters/labor" | "/chapters/power" | "/chapters/data" | "/chapters/work" | "/about";
  };
  "routes/chapters.tsx": {
    id: "routes/chapters";
    page: "/chapters" | "/chapters/shanawdithit" | "/chapters/description" | "/chapters/playfair" | "/chapters/peabody" | "/chapters/preface" | "/chapters/process" | "/chapters/dubois" | "/chapters/people" | "/chapters/image" | "/chapters/intro" | "/chapters/labor" | "/chapters/power" | "/chapters/data" | "/chapters/work";
  };
  "routes/chapters.shanawdithit.tsx": {
    id: "routes/chapters.shanawdithit";
    page: "/chapters/shanawdithit";
  };
  "routes/chapters.description.tsx": {
    id: "routes/chapters.description";
    page: "/chapters/description";
  };
  "routes/chapters.playfair.tsx": {
    id: "routes/chapters.playfair";
    page: "/chapters/playfair";
  };
  "routes/chapters.peabody.tsx": {
    id: "routes/chapters.peabody";
    page: "/chapters/peabody";
  };
  "routes/chapters.preface.tsx": {
    id: "routes/chapters.preface";
    page: "/chapters/preface";
  };
  "routes/chapters.process.tsx": {
    id: "routes/chapters.process";
    page: "/chapters/process";
  };
  "routes/chapters.dubois.tsx": {
    id: "routes/chapters.dubois";
    page: "/chapters/dubois";
  };
  "routes/chapters.people.tsx": {
    id: "routes/chapters.people";
    page: "/chapters/people";
  };
  "routes/chapters.image.tsx": {
    id: "routes/chapters.image";
    page: "/chapters/image";
  };
  "routes/chapters.intro.tsx": {
    id: "routes/chapters.intro";
    page: "/chapters/intro";
  };
  "routes/chapters.labor.tsx": {
    id: "routes/chapters.labor";
    page: "/chapters/labor";
  };
  "routes/chapters.power.tsx": {
    id: "routes/chapters.power";
    page: "/chapters/power";
  };
  "routes/chapters.data.tsx": {
    id: "routes/chapters.data";
    page: "/chapters/data";
  };
  "routes/chapters.work.tsx": {
    id: "routes/chapters.work";
    page: "/chapters/work";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};