export type TWeekData = {
  week: Date;
  GitHub: number;
  Zotero: number;
  "Google Drive": number;
  iCal: number;
  Figma: number;
  total: number;
  weekNum: number;
};

const weeklyData: { [key: string]: TWeekData[] } = {
  m7_2012: [
    {
      week: new Date(2012, 7, 20),
      GitHub: 0,
      Zotero: 1,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2012, 7, 6),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2012, 7, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2012, 7, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m11_2013: [
    {
      week: new Date(2013, 11, 9),
      GitHub: 0,
      Zotero: 57,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 57,
      weekNum: 2,
    },
    {
      week: new Date(2013, 11, 16),
      GitHub: 0,
      Zotero: 33,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 33,
      weekNum: 3,
    },
    {
      week: new Date(2013, 11, 30),
      GitHub: 0,
      Zotero: 5,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 5,
    },
    {
      week: new Date(2013, 11, 2),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2013, 11, 23),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m0_2014: [
    {
      week: new Date(2014, 0, 6),
      GitHub: 0,
      Zotero: 2,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 1,
    },
    {
      week: new Date(2014, 0, 20),
      GitHub: 0,
      Zotero: 1,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2014, 0, 27),
      GitHub: 0,
      Zotero: 1,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2014, 0, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m1_2014: [
    {
      week: new Date(2014, 1, 24),
      GitHub: 0,
      Zotero: 1,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2014, 1, 3),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2014, 1, 10),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2014, 1, 17),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m4_2014: [
    {
      week: new Date(2014, 4, 12),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 2,
    },
    {
      week: new Date(2014, 4, 26),
      GitHub: 0,
      Zotero: 1,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2014, 4, 5),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2014, 4, 19),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m11_2014: [
    {
      week: new Date(2014, 11, 15),
      GitHub: 0,
      Zotero: 2,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 3,
    },
    {
      week: new Date(2014, 11, 1),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2014, 11, 8),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2014, 11, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2014, 11, 29),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m2_2015: [
    {
      week: new Date(2015, 2, 9),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2015, 2, 2),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2015, 2, 16),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2015, 2, 23),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2015, 2, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m7_2015: [
    {
      week: new Date(2015, 7, 3),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2015, 7, 10),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2015, 7, 17),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2015, 7, 24),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2015, 7, 31),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m2_2016: [
    {
      week: new Date(2016, 2, 21),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 3,
    },
    {
      week: new Date(2016, 2, 7),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2016, 2, 14),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2016, 2, 28),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m3_2016: [
    {
      week: new Date(2016, 3, 4),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 1,
    },
    {
      week: new Date(2016, 3, 11),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2016, 3, 18),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2016, 3, 25),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m4_2016: [
    {
      week: new Date(2016, 4, 16),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 3,
    },
    {
      week: new Date(2016, 4, 2),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2016, 4, 9),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2016, 4, 23),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2016, 4, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m5_2016: [
    {
      week: new Date(2016, 5, 27),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2016, 5, 6),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2016, 5, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2016, 5, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m7_2016: [
    {
      week: new Date(2016, 7, 8),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2016, 7, 1),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2016, 7, 15),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2016, 7, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2016, 7, 29),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m8_2016: [
    {
      week: new Date(2016, 8, 5),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 1,
    },
    {
      week: new Date(2016, 8, 12),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2016, 8, 19),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 3,
    },
    {
      week: new Date(2016, 8, 26),
      GitHub: 7,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 7,
      weekNum: 4,
    },
  ],
  m9_2016: [
    {
      week: new Date(2016, 9, 3),
      GitHub: 9,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 11,
      weekNum: 1,
    },
    {
      week: new Date(2016, 9, 10),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 2,
    },
    {
      week: new Date(2016, 9, 24),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 3,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 4,
    },
    {
      week: new Date(2016, 9, 31),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 5,
    },
    {
      week: new Date(2016, 9, 17),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m10_2016: [
    {
      week: new Date(2016, 10, 7),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 1,
    },
    {
      week: new Date(2016, 10, 28),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2016, 10, 14),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2016, 10, 21),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m11_2016: [
    {
      week: new Date(2016, 11, 5),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2016, 11, 12),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2016, 11, 19),
      GitHub: 12,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 12,
      weekNum: 3,
    },
    {
      week: new Date(2016, 11, 26),
      GitHub: 13,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 13,
      weekNum: 4,
    },
  ],
  m0_2017: [
    {
      week: new Date(2017, 0, 2),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 1,
    },
    {
      week: new Date(2017, 0, 9),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 6,
      weekNum: 2,
    },
    {
      week: new Date(2017, 0, 16),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 3,
    },
    {
      week: new Date(2017, 0, 23),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 4,
    },
    {
      week: new Date(2017, 0, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m1_2017: [
    {
      week: new Date(2017, 1, 6),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2017, 1, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2017, 1, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2017, 1, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m2_2017: [
    {
      week: new Date(2017, 2, 6),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 1,
    },
    {
      week: new Date(2017, 2, 13),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 2,
    },
    {
      week: new Date(2017, 2, 27),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 4,
    },
    {
      week: new Date(2017, 2, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m3_2017: [
    {
      week: new Date(2017, 3, 17),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 3,
    },
    {
      week: new Date(2017, 3, 3),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2017, 3, 10),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2017, 3, 24),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m4_2017: [
    {
      week: new Date(2017, 4, 15),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2017, 4, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2017, 4, 29),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 5,
    },
    {
      week: new Date(2017, 4, 1),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2017, 4, 8),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m5_2017: [
    {
      week: new Date(2017, 5, 5),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 2,
      Figma: 0,
      total: 2,
      weekNum: 1,
    },
    {
      week: new Date(2017, 5, 12),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2017, 5, 19),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2017, 5, 26),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m7_2017: [
    {
      week: new Date(2017, 7, 21),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2017, 7, 28),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2017, 7, 7),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2017, 7, 14),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m8_2017: [
    {
      week: new Date(2017, 8, 18),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2017, 8, 25),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2017, 8, 4),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2017, 8, 11),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m9_2017: [
    {
      week: new Date(2017, 9, 2),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2017, 9, 16),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2017, 9, 23),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2017, 9, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 5,
    },
    {
      week: new Date(2017, 9, 9),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m10_2017: [
    {
      week: new Date(2017, 10, 6),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2017, 10, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2017, 10, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 3,
    },
    {
      week: new Date(2017, 10, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m11_2017: [
    {
      week: new Date(2017, 11, 4),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2017, 11, 11),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2017, 11, 18),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2017, 11, 25),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m0_2018: [
    {
      week: new Date(2018, 0, 15),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2018, 0, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2018, 0, 1),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2018, 0, 8),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2018, 0, 29),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m1_2018: [
    {
      week: new Date(2018, 1, 5),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2018, 1, 12),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2018, 1, 19),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2018, 1, 26),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m3_2018: [
    {
      week: new Date(2018, 3, 23),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 4,
    },
    {
      week: new Date(2018, 3, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 0,
      total: 2,
      weekNum: 5,
    },
    {
      week: new Date(2018, 3, 2),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2018, 3, 9),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2018, 3, 16),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m4_2018: [
    {
      week: new Date(2018, 4, 7),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 1,
    },
    {
      week: new Date(2018, 4, 14),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 12,
      iCal: 0,
      Figma: 0,
      total: 12,
      weekNum: 2,
    },
    {
      week: new Date(2018, 4, 21),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2018, 4, 28),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m5_2018: [
    {
      week: new Date(2018, 5, 11),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 31,
      iCal: 0,
      Figma: 0,
      total: 31,
      weekNum: 2,
    },
    {
      week: new Date(2018, 5, 18),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2018, 5, 25),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 4,
    },
    {
      week: new Date(2018, 5, 4),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
  ],
  m6_2018: [
    {
      week: new Date(2018, 6, 9),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 7,
      weekNum: 2,
    },
    {
      week: new Date(2018, 6, 16),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2018, 6, 23),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2018, 6, 30),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 5,
    },
    {
      week: new Date(2018, 6, 2),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
  ],
  m7_2018: [
    {
      week: new Date(2018, 7, 6),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2018, 7, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2018, 7, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2018, 7, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m8_2018: [
    {
      week: new Date(2018, 8, 3),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 0,
      total: 2,
      weekNum: 1,
    },
    {
      week: new Date(2018, 8, 10),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2018, 8, 17),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2018, 8, 24),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
  ],
  m9_2018: [
    {
      week: new Date(2018, 9, 1),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 8,
      iCal: 0,
      Figma: 0,
      total: 8,
      weekNum: 1,
    },
    {
      week: new Date(2018, 9, 8),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2018, 9, 15),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2018, 9, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2018, 9, 29),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m10_2018: [
    {
      week: new Date(2018, 10, 26),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 4,
    },
    {
      week: new Date(2018, 10, 5),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2018, 10, 12),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2018, 10, 19),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m11_2018: [
    {
      week: new Date(2018, 11, 3),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2018, 11, 10),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2018, 11, 17),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2018, 11, 24),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2018, 11, 31),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m0_2019: [
    {
      week: new Date(2019, 0, 7),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 7,
      iCal: 0,
      Figma: 0,
      total: 7,
      weekNum: 1,
    },
    {
      week: new Date(2019, 0, 21),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 3,
    },
    {
      week: new Date(2019, 0, 28),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 4,
    },
    {
      week: new Date(2019, 0, 14),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m1_2019: [
    {
      week: new Date(2019, 1, 4),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 1,
    },
    {
      week: new Date(2019, 1, 11),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2019, 1, 18),
      GitHub: 13,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 13,
      weekNum: 3,
    },
    {
      week: new Date(2019, 1, 25),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 4,
    },
  ],
  m2_2019: [
    {
      week: new Date(2019, 2, 4),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 1,
    },
    {
      week: new Date(2019, 2, 25),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2019, 2, 11),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2019, 2, 18),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m3_2019: [
    {
      week: new Date(2019, 3, 1),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2019, 3, 8),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2019, 3, 15),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2019, 3, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2019, 3, 29),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m4_2019: [
    {
      week: new Date(2019, 4, 20),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 3,
    },
    {
      week: new Date(2019, 4, 27),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2019, 4, 6),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2019, 4, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m5_2019: [
    {
      week: new Date(2019, 5, 17),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2019, 5, 3),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2019, 5, 10),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2019, 5, 24),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m6_2019: [
    {
      week: new Date(2019, 6, 15),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 3,
    },
    {
      week: new Date(2019, 6, 29),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 5,
    },
    {
      week: new Date(2019, 6, 1),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2019, 6, 8),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2019, 6, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m7_2019: [
    {
      week: new Date(2019, 7, 5),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2019, 7, 12),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2019, 7, 19),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2019, 7, 26),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m8_2019: [
    {
      week: new Date(2019, 8, 23),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2019, 8, 30),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 5,
    },
    {
      week: new Date(2019, 8, 2),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2019, 8, 9),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2019, 8, 16),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m9_2019: [
    {
      week: new Date(2019, 9, 14),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2019, 9, 7),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2019, 9, 21),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2019, 9, 28),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m10_2019: [
    {
      week: new Date(2019, 10, 11),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 6,
      weekNum: 2,
    },
    {
      week: new Date(2019, 10, 18),
      GitHub: 7,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 7,
      weekNum: 3,
    },
    {
      week: new Date(2019, 10, 4),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2019, 10, 25),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m11_2019: [
    {
      week: new Date(2019, 11, 9),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 2,
    },
    {
      week: new Date(2019, 11, 16),
      GitHub: 14,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 14,
      weekNum: 3,
    },
    {
      week: new Date(2019, 11, 2),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2019, 11, 23),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2019, 11, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m0_2020: [
    {
      week: new Date(2020, 0, 6),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2020, 0, 13),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 3,
      iCal: 1,
      Figma: 0,
      total: 5,
      weekNum: 2,
    },
    {
      week: new Date(2020, 0, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
    {
      week: new Date(2020, 0, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m1_2020: [
    {
      week: new Date(2020, 1, 3),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 1,
    },
    {
      week: new Date(2020, 1, 10),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 2,
    },
    {
      week: new Date(2020, 1, 24),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 4,
    },
    {
      week: new Date(2020, 1, 17),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m2_2020: [
    {
      week: new Date(2020, 2, 2),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 1,
    },
    {
      week: new Date(2020, 2, 9),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 2,
    },
    {
      week: new Date(2020, 2, 23),
      GitHub: 7,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 7,
      weekNum: 4,
    },
    {
      week: new Date(2020, 2, 30),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 3,
      weekNum: 5,
    },
    {
      week: new Date(2020, 2, 16),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m3_2020: [
    {
      week: new Date(2020, 3, 6),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 1,
    },
    {
      week: new Date(2020, 3, 27),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2020, 3, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2020, 3, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m4_2020: [
    {
      week: new Date(2020, 4, 4),
      GitHub: 9,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 11,
      weekNum: 1,
    },
    {
      week: new Date(2020, 4, 11),
      GitHub: 18,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 18,
      weekNum: 2,
    },
    {
      week: new Date(2020, 4, 18),
      GitHub: 14,
      Zotero: 0,
      "Google Drive": 6,
      iCal: 0,
      Figma: 0,
      total: 20,
      weekNum: 3,
    },
    {
      week: new Date(2020, 4, 25),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 4,
      weekNum: 4,
    },
  ],
  m5_2020: [
    {
      week: new Date(2020, 5, 1),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 1,
    },
    {
      week: new Date(2020, 5, 8),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 2,
    },
    {
      week: new Date(2020, 5, 15),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 7,
      weekNum: 3,
    },
    {
      week: new Date(2020, 5, 22),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 4,
    },
    {
      week: new Date(2020, 5, 29),
      GitHub: 9,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 9,
      weekNum: 5,
    },
  ],
  m6_2020: [
    {
      week: new Date(2020, 6, 6),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 1,
    },
    {
      week: new Date(2020, 6, 13),
      GitHub: 10,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 12,
      weekNum: 2,
    },
    {
      week: new Date(2020, 6, 20),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2020, 6, 27),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 4,
    },
  ],
  m7_2020: [
    {
      week: new Date(2020, 7, 3),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 1,
    },
    {
      week: new Date(2020, 7, 10),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 6,
      weekNum: 2,
    },
    {
      week: new Date(2020, 7, 17),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 4,
      iCal: 0,
      Figma: 0,
      total: 6,
      weekNum: 3,
    },
    {
      week: new Date(2020, 7, 24),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 53,
      iCal: 1,
      Figma: 0,
      total: 57,
      weekNum: 4,
    },
    {
      week: new Date(2020, 7, 31),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 5,
    },
  ],
  m8_2020: [
    {
      week: new Date(2020, 8, 7),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 12,
      iCal: 0,
      Figma: 0,
      total: 15,
      weekNum: 1,
    },
    {
      week: new Date(2020, 8, 14),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 6,
      weekNum: 2,
    },
    {
      week: new Date(2020, 8, 21),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 3,
    },
    {
      week: new Date(2020, 8, 28),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
  ],
  m9_2020: [
    {
      week: new Date(2020, 9, 12),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 3,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 2,
    },
    {
      week: new Date(2020, 9, 19),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2020, 9, 26),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2020, 9, 5),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
  ],
  m10_2020: [
    {
      week: new Date(2020, 10, 2),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 34,
      iCal: 0,
      Figma: 0,
      total: 35,
      weekNum: 1,
    },
    {
      week: new Date(2020, 10, 9),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 4,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 2,
    },
    {
      week: new Date(2020, 10, 16),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 3,
    },
    {
      week: new Date(2020, 10, 23),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
    {
      week: new Date(2020, 10, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m11_2020: [
    {
      week: new Date(2020, 11, 7),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 1,
    },
    {
      week: new Date(2020, 11, 14),
      GitHub: 17,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 17,
      weekNum: 2,
    },
    {
      week: new Date(2020, 11, 21),
      GitHub: 33,
      Zotero: 0,
      "Google Drive": 10,
      iCal: 0,
      Figma: 0,
      total: 43,
      weekNum: 3,
    },
    {
      week: new Date(2020, 11, 28),
      GitHub: 33,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 33,
      weekNum: 4,
    },
  ],
  m0_2021: [
    {
      week: new Date(2021, 0, 4),
      GitHub: 30,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 32,
      weekNum: 1,
    },
    {
      week: new Date(2021, 0, 11),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2021, 0, 25),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 4,
    },
    {
      week: new Date(2021, 0, 18),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m1_2021: [
    {
      week: new Date(2021, 1, 15),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 1,
      total: 5,
      weekNum: 3,
    },
    {
      week: new Date(2021, 1, 22),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 4,
      total: 6,
      weekNum: 4,
    },
    {
      week: new Date(2021, 1, 1),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
    {
      week: new Date(2021, 1, 8),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m2_2021: [
    {
      week: new Date(2021, 2, 1),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 7,
      total: 10,
      weekNum: 1,
    },
    {
      week: new Date(2021, 2, 8),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 2,
      total: 4,
      weekNum: 2,
    },
    {
      week: new Date(2021, 2, 15),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 3,
    },
    {
      week: new Date(2021, 2, 22),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 7,
      weekNum: 4,
    },
    {
      week: new Date(2021, 2, 29),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 19,
      iCal: 0,
      Figma: 15,
      total: 38,
      weekNum: 5,
    },
  ],
  m3_2021: [
    {
      week: new Date(2021, 3, 5),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 5,
      total: 8,
      weekNum: 1,
    },
    {
      week: new Date(2021, 3, 12),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 7,
      weekNum: 2,
    },
    {
      week: new Date(2021, 3, 19),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 13,
      total: 13,
      weekNum: 3,
    },
    {
      week: new Date(2021, 3, 26),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 4,
      weekNum: 4,
    },
  ],
  m4_2021: [
    {
      week: new Date(2021, 4, 3),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 1,
      total: 2,
      weekNum: 1,
    },
    {
      week: new Date(2021, 4, 10),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 7,
      total: 7,
      weekNum: 2,
    },
    {
      week: new Date(2021, 4, 17),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 9,
      total: 9,
      weekNum: 3,
    },
    {
      week: new Date(2021, 4, 24),
      GitHub: 8,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 4,
      total: 13,
      weekNum: 4,
    },
    {
      week: new Date(2021, 4, 31),
      GitHub: 14,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 1,
      total: 16,
      weekNum: 5,
    },
  ],
  m5_2021: [
    {
      week: new Date(2021, 5, 7),
      GitHub: 24,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 5,
      total: 31,
      weekNum: 1,
    },
    {
      week: new Date(2021, 5, 14),
      GitHub: 35,
      Zotero: 0,
      "Google Drive": 3,
      iCal: 0,
      Figma: 0,
      total: 38,
      weekNum: 2,
    },
    {
      week: new Date(2021, 5, 21),
      GitHub: 14,
      Zotero: 0,
      "Google Drive": 55,
      iCal: 0,
      Figma: 9,
      total: 78,
      weekNum: 3,
    },
    {
      week: new Date(2021, 5, 28),
      GitHub: 14,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 22,
      total: 37,
      weekNum: 4,
    },
  ],
  m6_2021: [
    {
      week: new Date(2021, 6, 5),
      GitHub: 39,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 4,
      total: 43,
      weekNum: 1,
    },
    {
      week: new Date(2021, 6, 12),
      GitHub: 8,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 22,
      total: 31,
      weekNum: 2,
    },
    {
      week: new Date(2021, 6, 19),
      GitHub: 16,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 4,
      total: 20,
      weekNum: 3,
    },
    {
      week: new Date(2021, 6, 26),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 9,
      total: 9,
      weekNum: 4,
    },
  ],
  m7_2021: [
    {
      week: new Date(2021, 7, 2),
      GitHub: 14,
      Zotero: 0,
      "Google Drive": 10,
      iCal: 1,
      Figma: 3,
      total: 28,
      weekNum: 1,
    },
    {
      week: new Date(2021, 7, 9),
      GitHub: 9,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 10,
      weekNum: 2,
    },
    {
      week: new Date(2021, 7, 16),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2021, 7, 23),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 4,
    },
    {
      week: new Date(2021, 7, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 5,
    },
  ],
  m8_2021: [
    {
      week: new Date(2021, 8, 13),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 3,
      Figma: 3,
      total: 9,
      weekNum: 2,
    },
    {
      week: new Date(2021, 8, 20),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 4,
      total: 6,
      weekNum: 3,
    },
    {
      week: new Date(2021, 8, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 0,
      total: 2,
      weekNum: 4,
    },
    {
      week: new Date(2021, 8, 6),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
  ],
  m9_2021: [
    {
      week: new Date(2021, 9, 4),
      GitHub: 7,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 4,
      total: 12,
      weekNum: 1,
    },
    {
      week: new Date(2021, 9, 11),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 3,
      total: 8,
      weekNum: 2,
    },
    {
      week: new Date(2021, 9, 18),
      GitHub: 10,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 12,
      weekNum: 3,
    },
    {
      week: new Date(2021, 9, 25),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 2,
      total: 7,
      weekNum: 4,
    },
  ],
  m10_2021: [
    {
      week: new Date(2021, 10, 1),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 2,
      total: 8,
      weekNum: 1,
    },
    {
      week: new Date(2021, 10, 8),
      GitHub: 7,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 1,
      total: 10,
      weekNum: 2,
    },
    {
      week: new Date(2021, 10, 15),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 64,
      iCal: 0,
      Figma: 0,
      total: 65,
      weekNum: 3,
    },
    {
      week: new Date(2021, 10, 22),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 4,
      weekNum: 4,
    },
    {
      week: new Date(2021, 10, 29),
      GitHub: 7,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 8,
      weekNum: 5,
    },
  ],
  m11_2021: [
    {
      week: new Date(2021, 11, 6),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 4,
      weekNum: 1,
    },
    {
      week: new Date(2021, 11, 13),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 2,
      weekNum: 2,
    },
    {
      week: new Date(2021, 11, 27),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 7,
      iCal: 0,
      Figma: 2,
      total: 10,
      weekNum: 4,
    },
    {
      week: new Date(2021, 11, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m0_2022: [
    {
      week: new Date(2022, 0, 3),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 5,
      total: 6,
      weekNum: 1,
    },
    {
      week: new Date(2022, 0, 10),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 3,
      weekNum: 2,
    },
    {
      week: new Date(2022, 0, 17),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2022, 0, 24),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 4,
      total: 5,
      weekNum: 4,
    },
    {
      week: new Date(2022, 0, 31),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 5,
    },
  ],
  m1_2022: [
    {
      week: new Date(2022, 1, 7),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 7,
      total: 15,
      weekNum: 1,
    },
    {
      week: new Date(2022, 1, 14),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 3,
      total: 6,
      weekNum: 2,
    },
    {
      week: new Date(2022, 1, 21),
      GitHub: 8,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 8,
      weekNum: 3,
    },
    {
      week: new Date(2022, 1, 28),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 2,
      total: 10,
      weekNum: 5,
    },
  ],
  m2_2022: [
    {
      week: new Date(2022, 2, 7),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 1,
    },
    {
      week: new Date(2022, 2, 14),
      GitHub: 14,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 3,
      total: 18,
      weekNum: 2,
    },
    {
      week: new Date(2022, 2, 21),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 1,
      total: 4,
      weekNum: 3,
    },
    {
      week: new Date(2022, 2, 28),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 3,
      iCal: 1,
      Figma: 4,
      total: 9,
      weekNum: 4,
    },
  ],
  m3_2022: [
    {
      week: new Date(2022, 3, 11),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 6,
      total: 11,
      weekNum: 2,
    },
    {
      week: new Date(2022, 3, 18),
      GitHub: 12,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 4,
      total: 17,
      weekNum: 3,
    },
    {
      week: new Date(2022, 3, 25),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 2,
      total: 4,
      weekNum: 4,
    },
    {
      week: new Date(2022, 3, 4),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 1,
    },
  ],
  m4_2022: [
    {
      week: new Date(2022, 4, 2),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 0,
      total: 3,
      weekNum: 1,
    },
    {
      week: new Date(2022, 4, 9),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 1,
      Figma: 0,
      total: 4,
      weekNum: 2,
    },
    {
      week: new Date(2022, 4, 16),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 2,
      total: 7,
      weekNum: 3,
    },
    {
      week: new Date(2022, 4, 23),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 6,
      iCal: 0,
      Figma: 0,
      total: 8,
      weekNum: 4,
    },
    {
      week: new Date(2022, 4, 30),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 8,
      iCal: 1,
      Figma: 0,
      total: 9,
      weekNum: 5,
    },
  ],
  m5_2022: [
    {
      week: new Date(2022, 5, 6),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 4,
      total: 5,
      weekNum: 1,
    },
    {
      week: new Date(2022, 5, 13),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 5,
      total: 7,
      weekNum: 2,
    },
    {
      week: new Date(2022, 5, 20),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 13,
      iCal: 0,
      Figma: 9,
      total: 27,
      weekNum: 3,
    },
    {
      week: new Date(2022, 5, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 6,
      iCal: 0,
      Figma: 4,
      total: 10,
      weekNum: 4,
    },
  ],
  m6_2022: [
    {
      week: new Date(2022, 6, 4),
      GitHub: 20,
      Zotero: 0,
      "Google Drive": 4,
      iCal: 1,
      Figma: 8,
      total: 33,
      weekNum: 1,
    },
    {
      week: new Date(2022, 6, 11),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 5,
      iCal: 0,
      Figma: 0,
      total: 5,
      weekNum: 2,
    },
    {
      week: new Date(2022, 6, 18),
      GitHub: 11,
      Zotero: 0,
      "Google Drive": 53,
      iCal: 0,
      Figma: 17,
      total: 81,
      weekNum: 3,
    },
    {
      week: new Date(2022, 6, 25),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 4,
      total: 5,
      weekNum: 4,
    },
  ],
  m7_2022: [
    {
      week: new Date(2022, 7, 1),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 7,
      iCal: 0,
      Figma: 4,
      total: 12,
      weekNum: 1,
    },
    {
      week: new Date(2022, 7, 8),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 3,
      iCal: 0,
      Figma: 6,
      total: 10,
      weekNum: 2,
    },
    {
      week: new Date(2022, 7, 15),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 4,
      total: 6,
      weekNum: 3,
    },
    {
      week: new Date(2022, 7, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 1,
      total: 3,
      weekNum: 4,
    },
    {
      week: new Date(2022, 7, 29),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 5,
      total: 9,
      weekNum: 5,
    },
  ],
  m8_2022: [
    {
      week: new Date(2022, 8, 5),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 3,
      weekNum: 1,
    },
    {
      week: new Date(2022, 8, 12),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 3,
      weekNum: 2,
    },
    {
      week: new Date(2022, 8, 19),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 1,
      total: 7,
      weekNum: 3,
    },
    {
      week: new Date(2022, 8, 26),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 7,
      weekNum: 4,
    },
  ],
  m9_2022: [
    {
      week: new Date(2022, 9, 3),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 7,
      total: 9,
      weekNum: 1,
    },
    {
      week: new Date(2022, 9, 10),
      GitHub: 10,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 5,
      total: 15,
      weekNum: 2,
    },
    {
      week: new Date(2022, 9, 17),
      GitHub: 7,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 7,
      weekNum: 3,
    },
    {
      week: new Date(2022, 9, 24),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 4,
    },
    {
      week: new Date(2022, 9, 31),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 5,
    },
  ],
  m10_2022: [
    {
      week: new Date(2022, 10, 7),
      GitHub: 8,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 2,
      Figma: 13,
      total: 23,
      weekNum: 1,
    },
    {
      week: new Date(2022, 10, 14),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 2,
      weekNum: 2,
    },
    {
      week: new Date(2022, 10, 21),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 3,
      total: 7,
      weekNum: 3,
    },
    {
      week: new Date(2022, 10, 28),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 6,
      total: 11,
      weekNum: 4,
    },
  ],
  m11_2022: [
    {
      week: new Date(2022, 11, 5),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 1,
      weekNum: 1,
    },
    {
      week: new Date(2022, 11, 26),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 4,
    },
    {
      week: new Date(2022, 11, 12),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
    {
      week: new Date(2022, 11, 19),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 3,
    },
  ],
  m0_2023: [
    {
      week: new Date(2023, 0, 2),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 7,
      total: 9,
      weekNum: 1,
    },
    {
      week: new Date(2023, 0, 9),
      GitHub: 36,
      Zotero: 0,
      "Google Drive": 5,
      iCal: 0,
      Figma: 16,
      total: 57,
      weekNum: 2,
    },
    {
      week: new Date(2023, 0, 16),
      GitHub: 12,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 7,
      total: 19,
      weekNum: 3,
    },
    {
      week: new Date(2023, 0, 23),
      GitHub: 14,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 6,
      total: 21,
      weekNum: 4,
    },
    {
      week: new Date(2023, 0, 30),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 12,
      total: 18,
      weekNum: 5,
    },
  ],
  m1_2023: [
    {
      week: new Date(2023, 1, 6),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 13,
      total: 16,
      weekNum: 1,
    },
    {
      week: new Date(2023, 1, 13),
      GitHub: 19,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 4,
      total: 23,
      weekNum: 2,
    },
    {
      week: new Date(2023, 1, 20),
      GitHub: 9,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 5,
      total: 16,
      weekNum: 3,
    },
    {
      week: new Date(2023, 1, 27),
      GitHub: 11,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 9,
      total: 21,
      weekNum: 4,
    },
  ],
  m2_2023: [
    {
      week: new Date(2023, 2, 6),
      GitHub: 22,
      Zotero: 0,
      "Google Drive": 3,
      iCal: 3,
      Figma: 12,
      total: 40,
      weekNum: 1,
    },
    {
      week: new Date(2023, 2, 13),
      GitHub: 13,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 11,
      total: 25,
      weekNum: 2,
    },
    {
      week: new Date(2023, 2, 20),
      GitHub: 9,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 1,
      Figma: 15,
      total: 26,
      weekNum: 3,
    },
    {
      week: new Date(2023, 2, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 8,
      total: 9,
      weekNum: 4,
    },
  ],
  m3_2023: [
    {
      week: new Date(2023, 3, 3),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 1,
      Figma: 4,
      total: 9,
      weekNum: 1,
    },
    {
      week: new Date(2023, 3, 10),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 2,
      Figma: 0,
      total: 7,
      weekNum: 2,
    },
    {
      week: new Date(2023, 3, 17),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 8,
      total: 8,
      weekNum: 3,
    },
    {
      week: new Date(2023, 3, 24),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 20,
      total: 25,
      weekNum: 4,
    },
  ],
  m4_2023: [
    {
      week: new Date(2023, 4, 1),
      GitHub: 9,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 3,
      total: 12,
      weekNum: 1,
    },
    {
      week: new Date(2023, 4, 8),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 5,
      weekNum: 2,
    },
    {
      week: new Date(2023, 4, 15),
      GitHub: 12,
      Zotero: 0,
      "Google Drive": 8,
      iCal: 1,
      Figma: 3,
      total: 24,
      weekNum: 3,
    },
    {
      week: new Date(2023, 4, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 8,
      iCal: 1,
      Figma: 1,
      total: 10,
      weekNum: 4,
    },
    {
      week: new Date(2023, 4, 29),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 6,
      iCal: 0,
      Figma: 2,
      total: 13,
      weekNum: 5,
    },
  ],
  m5_2023: [
    {
      week: new Date(2023, 5, 5),
      GitHub: 12,
      Zotero: 0,
      "Google Drive": 4,
      iCal: 5,
      Figma: 15,
      total: 36,
      weekNum: 1,
    },
    {
      week: new Date(2023, 5, 12),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 3,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 2,
    },
    {
      week: new Date(2023, 5, 19),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 2,
      Figma: 7,
      total: 14,
      weekNum: 3,
    },
    {
      week: new Date(2023, 5, 26),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 1,
      Figma: 4,
      total: 7,
      weekNum: 4,
    },
  ],
  m6_2023: [
    {
      week: new Date(2023, 6, 3),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 6,
      weekNum: 1,
    },
    {
      week: new Date(2023, 6, 10),
      GitHub: 1,
      Zotero: 10,
      "Google Drive": 10,
      iCal: 1,
      Figma: 0,
      total: 22,
      weekNum: 2,
    },
    {
      week: new Date(2023, 6, 17),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 1,
      total: 7,
      weekNum: 3,
    },
    {
      week: new Date(2023, 6, 24),
      GitHub: 5,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 6,
      weekNum: 4,
    },
    {
      week: new Date(2023, 6, 31),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 3,
      weekNum: 5,
    },
  ],
  m7_2023: [
    {
      week: new Date(2023, 7, 7),
      GitHub: 10,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 10,
      weekNum: 1,
    },
    {
      week: new Date(2023, 7, 14),
      GitHub: 2,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 0,
      total: 3,
      weekNum: 2,
    },
    {
      week: new Date(2023, 7, 21),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 13,
      iCal: 2,
      Figma: 2,
      total: 18,
      weekNum: 3,
    },
    {
      week: new Date(2023, 7, 28),
      GitHub: 25,
      Zotero: 0,
      "Google Drive": 20,
      iCal: 1,
      Figma: 4,
      total: 50,
      weekNum: 4,
    },
  ],
  m8_2023: [
    {
      week: new Date(2023, 8, 4),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 1,
      Figma: 1,
      total: 6,
      weekNum: 1,
    },
    {
      week: new Date(2023, 8, 11),
      GitHub: 3,
      Zotero: 0,
      "Google Drive": 5,
      iCal: 1,
      Figma: 2,
      total: 11,
      weekNum: 2,
    },
    {
      week: new Date(2023, 8, 18),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 3,
    },
    {
      week: new Date(2023, 8, 25),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 19,
      iCal: 1,
      Figma: 0,
      total: 20,
      weekNum: 4,
    },
  ],
  m9_2023: [
    {
      week: new Date(2023, 9, 2),
      GitHub: 9,
      Zotero: 0,
      "Google Drive": 8,
      iCal: 0,
      Figma: 13,
      total: 30,
      weekNum: 1,
    },
    {
      week: new Date(2023, 9, 16),
      GitHub: 13,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 5,
      total: 18,
      weekNum: 3,
    },
    {
      week: new Date(2023, 9, 23),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 4,
      iCal: 0,
      Figma: 4,
      total: 14,
      weekNum: 4,
    },
    {
      week: new Date(2023, 9, 30),
      GitHub: 10,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 3,
      total: 14,
      weekNum: 5,
    },
    {
      week: new Date(2023, 9, 9),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 2,
    },
  ],
  m10_2023: [
    {
      week: new Date(2023, 10, 6),
      GitHub: 16,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 18,
      weekNum: 1,
    },
    {
      week: new Date(2023, 10, 13),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 1,
      weekNum: 2,
    },
    {
      week: new Date(2023, 10, 20),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 1,
      weekNum: 3,
    },
    {
      week: new Date(2023, 10, 27),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 0,
      weekNum: 4,
    },
  ],
  m11_2023: [
    {
      week: new Date(2023, 11, 4),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 0,
      total: 2,
      weekNum: 1,
    },
    {
      week: new Date(2023, 11, 11),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 2,
      weekNum: 2,
    },
    {
      week: new Date(2023, 11, 18),
      GitHub: 8,
      Zotero: 0,
      "Google Drive": 2,
      iCal: 0,
      Figma: 3,
      total: 13,
      weekNum: 3,
    },
    {
      week: new Date(2023, 11, 25),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 1,
      total: 1,
      weekNum: 4,
    },
  ],
  m0_2024: [
    {
      week: new Date(2024, 0, 1),
      GitHub: 4,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 0,
      total: 4,
      weekNum: 1,
    },
    {
      week: new Date(2024, 0, 8),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 2,
      total: 2,
      weekNum: 2,
    },
    {
      week: new Date(2024, 0, 15),
      GitHub: 6,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 11,
      total: 18,
      weekNum: 3,
    },
    {
      week: new Date(2024, 0, 22),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 7,
      total: 7,
      weekNum: 4,
    },
    {
      week: new Date(2024, 0, 29),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 4,
      total: 5,
      weekNum: 5,
    },
  ],
  m1_2024: [
    {
      week: new Date(2024, 1, 5),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 6,
      total: 7,
      weekNum: 1,
    },
    {
      week: new Date(2024, 1, 12),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 7,
      total: 8,
      weekNum: 2,
    },
    {
      week: new Date(2024, 1, 19),
      GitHub: 0,
      Zotero: 0,
      "Google Drive": 18,
      iCal: 0,
      Figma: 2,
      total: 20,
      weekNum: 3,
    },
    {
      week: new Date(2024, 1, 26),
      GitHub: 22,
      Zotero: 0,
      "Google Drive": 0,
      iCal: 0,
      Figma: 6,
      total: 28,
      weekNum: 4,
    },
  ],
  m2_2024: [
    {
      week: new Date(2024, 2, 4),
      GitHub: 8,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 6,
      total: 15,
      weekNum: 1,
    },
    {
      week: new Date(2024, 2, 11),
      GitHub: 12,
      Zotero: 0,
      "Google Drive": 1,
      iCal: 0,
      Figma: 17,
      total: 30,
      weekNum: 2,
    },
    {
      week: new Date(2024, 2, 18),
      GitHub: 12,
      Zotero: 0,
      "Google Drive": 8,
      iCal: 0,
      Figma: 15,
      total: 35,
      weekNum: 3,
    },
    {
      week: new Date(2024, 2, 25),
      GitHub: 18,
      Zotero: 0,
      "Google Drive": 6,
      iCal: 0,
      Figma: 27,
      total: 51,
      weekNum: 4,
    },
  ],
  m3_2024: [
    {
      week: new Date(2024, 3, 1),
      GitHub: 20,
      Zotero: 0,
      "Google Drive": 101,
      iCal: 0,
      Figma: 25,
      total: 146,
      weekNum: 1,
    },
    {
      week: new Date(2024, 3, 8),
      GitHub: 1,
      Zotero: 0,
      "Google Drive": 5,
      iCal: 0,
      Figma: 3,
      total: 9,
      weekNum: 2,
    },
  ],
};

export default weeklyData;
