export type TFigure = {
  chapter: string;
  fileName: string;
  title: string | undefined | null;
  artist: string | undefined | null;
  caption: string | undefined | null;
  altText: string | undefined | null;
  sensitive: boolean | string | undefined | null;
  sensitiveAltText: string | undefined | null;
  creditLine: string | undefined | null;
  digitizedLine: string | undefined | null;
  source: string | undefined | null;
  sourceUrl: string | undefined | null;
  fee: boolean | string | undefined | null;
  notes: string | undefined | null;
  frontPage: boolean | string | undefined | null;
  year: number;
  width: number | null;
  height: number | null;
  iiif: boolean;
  cleanCaption: string | undefined | null;
  cleanAltText: string | undefined | null;
  cleanSensitiveAltText: string | undefined | null;
  cleanTitle: string | string | undefined | null;
};
